### ISSUE TITLE
Appointments' linked objects

### ISSUE THREAD

**Issue by uatisdeproblem** [iter-idea/IDEA-Ionic8-extra#8]
> Come utente,
> voglio poter collegare specifici oggetti (come le attività di Arthur/Scarlett) ai vari appuntamenti dell'agenda
> per poter aggiungere informazioni all'agenda e renderla più fruibile

- [x] Attualmente, il colore di background di un appuntamento dipende dal colore del calendario; scegliere un colore generico (in contrasto con lo sfondo dell'agenda) e spostare l'informazione del colore (insieme al nome del calendario) nel formato delle label di una card di Trello. (#10)

> ![Schermata 2020-01-15 alle 17 55 15](https://user-images.githubusercontent.com/3777036/72453931-37583e80-37c0-11ea-9919-43811d0ebe17.png)

- [x] `IdeaX.AppointmentLinkedObject` dovrà essere variato: rimuovere `name` e inserire un nuovo attributo `type`, ovvero un enum che includa inizialmente: SCARLETT_ACTIVITY e ARTHUR_ACTIVITY. (#11)
- [x] Nella rappresentazione di ogni appuntamento sul calendario dovranno essere visualizzati i linked object; tale visualizzazione sarà molto simile a quella dei widget nel fronte delle card di Trello (vedi sotto). In particolare, dovrà essere visualizzata: l'icona del servizio dell'oggetti collegato (e.g. Arthur o Scarlett), un colore particolare e una serie di icone; questi ultimi due attributi assumeranno un significato in base al servizio. Per esempio, nel caso di Scarlett il colore evidenzierà il modello attività, mentre le icone rappresenteranno lo stato del rapportino collegato (bozza/confermato e inviato). Pertanto, per ogni appuntamento visibile in interfaccia agenda (in base alla modalità), dovrà essere effettuata una chiamata async che richieda i dati dei linkedObject coinvolti. (#11)
> ![Schermata 2020-01-15 alle 17 58 59](https://user-images.githubusercontent.com/3777036/72454210-bcdbee80-37c0-11ea-8121-d72725b5a672.png)
- [x] Sarà necessaria una struttura di appoggio che, in base al servizio di ogni linkedObject, valorizzi (#11):

```
name: string;
description: string;
color: string;
icons: Array<string>; // ion-icons
```
- [x] Toccando un appuntamento, come ora, verrà aperta la maschera per gestirlo. A questa sarà aggiunto un bottone per poter collegare un oggetto; questa procedura varierà a seconda del servizio da cui accediamo all'agenda (e.g. Arthur o Scarlett), facendo l'eventEmitter di un metodo che permetta di selezionare l'oggetto da collegare all'appuntamento. (#12)
- [x] Dalle maschera di modifica appuntamento sarà possibile visualizzare tutti gli oggetti collegati. Per ognuno di questi verrà fatta una chiamata API che valorizzerà un widget (vedi esempio Trello sotto) e visualizzerà, a seconda del servizio dell'oggetto collegato, una serie di informazioni (vedi attributi punto successivo). (#12)
> ![Schermata 2020-01-15 alle 18 06 48](https://user-images.githubusercontent.com/3777036/72454785-d3cf1080-37c1-11ea-84f2-893d452910b5.png)
- [x] Dalla stessa maschera si potrà anche rimuovere un oggetto collegato. (#12)
- [x] Valutare la possibilità di scatenare un'azione specifica quando si clicca direttamente su un linkedObject dalla rappresentazione grafica dell'appuntamento (e.g. apro attività di Scarlett collegata). (#12)
